name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      # Sử dụng mvnw có sẵn trong project của bạn
      run: ./mvnw clean package

    - name: Build Docker Image
      # Bước này chạy thử Dockerfile bạn đã viết để đảm bảo nó không lỗi
      run: docker build -t nguyentansang/ccptpm:latest .
